standard-things/esm

- README.md
Just a note for #57 that `import { namedExport } from "commonjs"` works in the REPL.
> Added note to README that named imports work for CommonJS modules

- README.md
Per @jdalton in #69 it is recommended to add `.esm-cache` to `.gitignore`.
> Add instruction to include .esm-cache in .gitignore

- .babelrc.js
- webpack.config.js
babelrc is (soon to be deprecated and) replaced by babelrc.js, which is similar to eslintrc.js
see: https://babeljs.io/blog/2017/09/12/planning-for-7.0
that also makes the _debug_ injection for babel config options more straightforward, and babelrc doesn't need to be explicitly required.
as a side note:
I got a _git commit_ hook exception from eslint:
```
/dev/github/esm_fork/test/fixture/scenario/jest/__tests__/test.js
6:2  error  'expect' is not defined  no-undef
✖ 1 problem (1 error, 0 warnings)
```
do you want to add _expect_ to the eslint allowed globals, or rather have the folder or file in eslintignore?
> use .babelrc.js instead of deprecated .babelrc

- src/acorn-ext/function-params-start.js
- src/parser.js
- src/visitor/import-export.js
- test/output/anon-async-function/actual.mjs
- test/output/anon-async-function/expected.mjs
- test/output/anon-function/actual.mjs
- test/output/anon-function/expected.mjs
- test/output/anon-generator/actual.mjs
- test/output/anon-generator/expected.mjs
A bug with the regexp I used in https://github.com/standard-things/esm/pull/187 was reported at https://github.com/rollup/rollup/issues/1798.
This PR implements an Acorn plugin to get the position of the parameters start, where the `default` is should be inserted.
> Use acorn to get the position where to inser the id of an anonymous function decl

- README.md
follow up from: https://github.com/standard-things/esm/issues/199
clarification for top-level _await_ support in ESM and CJS, also noting that Node v7.6+ is required.
> README.md clarify top-level await usage

- test/dynamic-import-tests.mjs
added some tests which should not be allowed if _import()_ is not a function. Not sure if any already exist.
removed 2 parameters to the _one argument only_ tests, because they fail for a different reason: moved _call_ to syntactic form tests, and removed .then because it's unrelated to arguments as well (unless the test is looking for import not having a test prototype method - but even in that case it would be not related to arguments).
I'd also like to move the spread test, since it's more or less also unrelated, at least in the case of having at least _one argument_ ( import(...['./some-file'] ). I think the latest on that matter is that the spread operator is just not allowed.
_regarding the test description_:
Domenic Denicola's proposal mentions a _syntactic form_ …
> adding tests for import() being a 'syntactic form'

- test/dynamic-import-tests.mjs
- test/fixture/comment/multi-line.js
- test/fixture/comment/single-line.js
failing test case for https://github.com/standard-things/esm/issues/203
**note:** 1st test run without cache works, 2nd test run with _cache_ fails.
``` js
Promise
.all([
cleanRepo(),
setupNode()
])
.then(() => runTests()) // works
.then(() => runTests(true)) // fails
```
> adding test case for bug when comment is preceding import()

- README.md
Since Jasmine loads each spec script directly to run it, it requires @std/esm be loaded by a custom runner such as the following:
```javascript
require = require("@std/esm")(module);
const Jasmine = require('jasmine');
const jasmine = new Jasmine();
jasmine.execute();
```
I linked to the Jasmine documentation rather than include a large blurb like the above to maintain the current style of the document.
> Add custom runner tip for Jasmine

- README.md
setting a path to the cache directory as depicted here: https://github.com/standard-things/esm/issues/215 is undocumented.
> added documentation for using cache option as path to directory

- .babelrc.js
- package.json
minimum supported node version is [v6.0](https://github.com/standard-things/esm/releases/tag/0.23.0). this changes the babel preset target to node 6.
_edit:_
plugin usage changes from:
transform-arrow-functions { "node":"4" }
transform-block-scoping { "node":"4" }
transform-destructuring { "node":"4" }
transform-parameters { "node":"4" }
transform-spread { "node":"4" }
transform-sticky-regex { "node":"4" }
transform-unicode-regex { "node":"4" }
transform-exponentiation-operator { "node":"4" }
transform-dotall-regex { "node":"4" }
to:
transform-destructuring { "node":"6" }
transform-exponentiation-operator { "node":"6" }
transform-dotall-regex { "node":"6" }
> change babel preset target to node 6

- .babelrc.js
sorry, I missed those in the previous PR :/
remove some explicitly excluded transforms as they are not in the env preset for node:6
btw, I saw you added some transforms which are supported in V8 in node v6.0 back:
transform-arrow-functions
transform-block-scoping
transform-parameters
transform-spread
Is that for performance reasons? or not fully spec compliant in node v6.0?
> remove some explicitly excluded transforms

- test/fixture/scenario/nyc-mocha-cjs-bridge/add.js
- test/fixture/scenario/nyc-mocha-cjs-bridge/cwd.js
- test/fixture/scenario/nyc-mocha-cjs-bridge/require-add.js
- test/fixture/scenario/nyc-mocha-cjs-bridge/test.js
- test/scenario-tests.mjs
I branched this from 3.0.7 (d5cf035) just prior to the fix, and it consistently fails every time.  Merging it onto master it passes every time.  Without `nyc` the test was flaky.  I named the scenario `nyc-mocha-cjs-bridge`.
> Add nyc-mocha-cjs-bridge scenario test

- README.md
This is a follow-up to https://github.com/standard-things/esm/issues/358.
My primary misconception was actually that I didn't realize why both `index.js` and `main.js` were needed.  That's why I was confused as to why only `require` was used in `index.js` but yet somehow `import` and `export` were also supported.
Now I realize that `index.js` serves just to enable ESM mode, and all files imported from there on down now support any import/export style.
The `index`/`main` two-hop system is obvious and clean once I understood why it was being used, but this line in the docs just serves to make it clearer for people who just arrived on the readme with no prior knowledge of the library.
> Clarify docs further as to why index.js is needed before main.js

- README.md
using **nodemon** since I started using [std/]esm. it's working great together, even with babel-register. ideal for local development.
unfortunately I couldn't find any links or references regarding flags (other than --inspect), but I suppose it does a pass through with known node flags.
usage:
```
nodemon -r esm index.js
```
or:
```
nodemon -r esm -r @babel/register index.js
```
```
> adding nodemon to tips

- package.json
The prepare script is run when esm is installed as a GitHub dependency, and when running `npm install` in a local clone.
This way, `npm install standard-things/esm` will automatically compile the `esm/loader` file, making it easier to try bugfixes before esm is released.
> Add prepare script so esm can be installed from GitHub

- test/scenario-tests.mjs
after each test run I had some hanging pm2 processes.
if I run it 5 times, I had 5 ghost processes:
this PR should take care of it.
unfortunately _Promise.prototype.finally_ isn't available on all versions of node, it'll cleanup for a successful and unsuccessful run (and re-throws, if there was an error)
since we're not testing pm2 kill, trash etc. I wonder if we should rather use [before and after hooks](https://mochajs.org/#hooks). I think that's cleaner and might also be beneficial for other tests. What do you think?
> kill hanging pm2 process after test run

- src/builtin/console.js
- test/builtin-modules.js
- test/fixture/builtin-modules/console.js
- test/tests.js
not sure how stupid this test is, or if it's even necessary, or if there's a better way:
but hey, at least it fails before [this commit](https://github.com/standard-things/esm/commit/c23a6d5dec6251ad8a7ddb24c23cb99ea03a9067), so there won't be a regression.
@jdalton created under a new umbrella, but we can move it elsewhere.
> test that console.log works the same as in node [#555]

- .gitignore
- package-lock.json
- package.json
- script/test.js
- script/test262/bootstrap.js
- script/test262/clone.js
- script/test262/copy.js
- script/test262/file-extension.js
- script/test262/files.js
- test/tests.js
- test/vendor/test262/context.js
- test/vendor/test262/index.js
- test/vendor/test262/skiplist
- test/vendor/test262/wrapper.js
**work in progress**
_notes and questions coming soon_
just want to see some runs first :yum:
**update:**
alrighty, cool. looking pretty good so far! 
_btw, the folder structure etc. where test262 is being cloned into and modified to etc. should probably change. also the way the tests are run (right now as part of the whole test suite). we can separate it out and make it a separate run, or a combination thereof..._
couple things I'm noticing which are still to do:
~- [ ] use test262 frontmatter `features` class-fields-private~
_I'll add more later ..._
> WIP: initial attempt to run 'esm' against tc39/test262

- script/setup-test262.js
- test/test262/skiplist
adds [currently] 17 tests `262 tests` for **import.meta**
7 are passing
10 skipped
relevant issue/PR:
https://github.com/tc39/test262/issues/1342
https://github.com/tc39/test262/pull/1888
I think most tests are syntax related and would have to be fixed on Acorn's side of things?
> test262 import.meta tests

- test/fixture/main-hook/package/index.js
- test/fixture/main-hook/package/module-1/index.js
- test/fixture/main-hook/package/module-2/index.js
- test/main-hook-tests.mjs
tests for https://github.com/standard-things/esm/issues/717 and https://github.com/standard-things/esm/issues/551 
tests are failing running against `v3.1.4` and passing running against `v3.2.0` [head/master]
I don't know of another/better/quicker way of creating symlinks for multi platform environments.
there's some other failures in unrelated tests. I'll have to check what's causing this.
> tests for symlinked packages

- package.json
- script/test.js
If you prefer a more popular module, you could use "perish".
I made "p-fatal" to allow programs to handle their rejections
one "nextTick" later, to avoid some undue failures.
Fixes #753
> Make unhandled promise rejections in tests fatal on Node v10, v11

- README.md
The current link to mocha require options is incorrect. This updates it to the correct link.
> Update mocha link to require options

- src/entry.js
For `npm pack`ed modules, the mtime is ancient and so we use ctime instead
As discussed in https://github.com/standard-things/esm/issues/746#issuecomment-511160099
> Entry.initialize(): detect properTime
